// Re-export everything from core (consumer doesn't need to install both)
export * from '@avatar-engine/core'

// Styles — extracted to dist/styles.css by Vite
import './styles/avatar.css'

// React hooks
export { useAvatarChat } from './hooks/useAvatarChat'
export type { UseAvatarChatReturn, AvatarChatOptions } from './hooks/useAvatarChat'
export { useAvatarWebSocket } from './hooks/useAvatarWebSocket'
export type { UseAvatarWebSocketReturn } from './hooks/useAvatarWebSocket'
export { useWidgetMode } from './hooks/useWidgetMode'
export type { UseWidgetModeReturn, TransitionHandler } from './hooks/useWidgetMode'
export { useAvatarBust } from './hooks/useAvatarBust'
export type { UseAvatarBustReturn } from './hooks/useAvatarBust'
export { useFileUpload } from './hooks/useFileUpload'
export type { UseFileUploadReturn } from './hooks/useFileUpload'
export { useAvailableProviders } from './hooks/useAvailableProviders'
export { useAvatarThumb } from './hooks/useAvatarThumb'

// React components
export { AvatarWidget } from './components/AvatarWidget'
export { ChatPanel } from './components/ChatPanel'
export { CompactChat } from './components/CompactChat'
export { CompactHeader } from './components/CompactHeader'
export { CompactInput } from './components/CompactInput'
export { CompactMessages } from './components/CompactMessages'
export { StatusBar } from './components/StatusBar'
export { ProviderModelSelector } from './components/ProviderModelSelector'
export { SessionPanel } from './components/SessionPanel'
export { MessageBubble } from './components/MessageBubble'
export { MarkdownContent } from './components/MarkdownContent'
export { ThinkingIndicator } from './components/ThinkingIndicator'
export { ToolActivity } from './components/ToolActivity'
export { PermissionDialog } from './components/PermissionDialog'
export { SafetyModeSelector } from './components/SafetyModeSelector'
export { SafetyModal } from './components/SafetyModal'
export { AvatarBust } from './components/AvatarBust'
export { AvatarFab } from './components/AvatarFab'
export { AvatarPicker } from './components/AvatarPicker'
export { AvatarLogo } from './components/AvatarLogo'
export { CostTracker } from './components/CostTracker'
export { BreathingOrb } from './components/BreathingOrb'
export { OptionControl } from './components/OptionControl'

// Component prop types — for TypeScript consumers extending components
export type { AvatarWidgetProps } from './components/AvatarWidget'
export type { AvatarBustProps } from './components/AvatarBust'
export type { AvatarFabProps } from './components/AvatarFab'
export type { AvatarPickerProps } from './components/AvatarPicker'
export type { AvatarLogoProps } from './components/AvatarLogo'
export type { BreathingOrbProps } from './components/BreathingOrb'
export type { ChatPanelProps } from './components/ChatPanel'
export type { CompactChatProps } from './components/CompactChat'
export type { CompactHeaderProps } from './components/CompactHeader'
export type { CompactInputProps } from './components/CompactInput'
export type { CompactMessagesProps } from './components/CompactMessages'
export type { CostTrackerProps } from './components/CostTracker'
export type { MarkdownContentProps } from './components/MarkdownContent'
export type { MessageBubbleProps } from './components/MessageBubble'
export type { OptionControlProps } from './components/OptionControl'
export type { PermissionDialogProps } from './components/PermissionDialog'
export type { ProviderModelSelectorProps } from './components/ProviderModelSelector'
export type { SafetyModalProps } from './components/SafetyModal'
export type { SafetyModeSelectorProps } from './components/SafetyModeSelector'
export type { SessionPanelProps } from './components/SessionPanel'
export type { StatusBarProps } from './components/StatusBar'
export type { ThinkingIndicatorProps } from './components/ThinkingIndicator'
export type { ToolActivityProps } from './components/ToolActivity'
